FROM centos:6.8

# Run updates
RUN yum update -y

### Install ansible
# Install python prerequisites
RUN yum install -y python-dev python-pip
RUN pip install -U pip
RUN pip install ansible

# Create ansible inventory file
RUN mkdir -p /etc/ansible
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
